@OneTime.Api_HostAddress = http://localhost:5273


GET {{OneTime.Api_HostAddress}}/api/projects
Accept: application/json

###

POST {{OneTime.Api_HostAddress}}/api/TimeEntries
Content-Type: application/json
Accept: application/json
{
	"userId": 1,
	"projectId": 5,
	"date": "2025-11-20",
	"note": "Worked on API integration",
	"hours": 4,
  "timesheetId": 1
}

###

GET {{OneTime.Api_HostAddress}}/api/TimeEntries/user/3
Accept: application/json
###

GET {{OneTime.Api_HostAddress}}/api/TimeSheets/leader/4/team?startDate=2025-11-01&endDate=2025-11-30
Accept: application/json
###

POST {{OneTime.Api_HostAddress}}/api/Timesheets/update/2
Content-Type: application/json
Accept: application/json

{
  "leaderId": 4,
  "status": 0,
  "comment": "Looks good to me xD."
}

###
GET {{OneTime.Api_HostAddress}}/api/users
Accept: application/json
###

GET {{OneTime.Api_HostAddress}}/api/users/3
Accept: application/json
###

POST {{OneTime.Api_HostAddress}}/api/users
Content-Type: application/json

{
  "name": "Peter",
  "email": "PELE@jndata.dk",
  "password": "test123",
  "role": 2,
  "managerId": 4
}
###
POST {{OneTime.Api_HostAddress}}/api/users
Content-Type: application/json

{
  "name": "DummyTest",
  "email": "dummytest",
  "password": "dummytest",
  "role": 2,
  "managerId":4
}
###

POST http://localhost:5273/api/users
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin@jndata.dk",
  "password": "Admin",
  "role": 4,
  "managerId": null
}
###
PUT http://localhost:5273/api/users/3
Content-Type: application/json

{
  "name": "Marco Updated",
  "email": "mdg@jndata.dk",
  "password":"test",
  "role": 2,
  "managerId": 4
}
###
DELETE http://localhost:5273/api/users/12

### filtering logs afhængig af hvad man søger.. kan være efter entitytype, userid, dato osv.
GET {{OneTime.Api_HostAddress}}/api/AuditLogs?entityType=TimeEntry
Accept: application/json

### henter alle logs ..
GET {{OneTime.Api_HostAddress}}/api/AuditLogs/all
Accept: application/json
###

POST {{OneTime.Api_HostAddress}}/api/auths/register
Content-Type: application/json

{
  "name": "Employee Test",
  "email": "Employee@jndata.dk",
  "password": "!1234Test",
  "role": 2,
  "managerId": 13
}
###

POST {{OneTime.Api_HostAddress}}/api/auths/login
Content-Type: application/json

{
  "email": "manager@jndata.dk",
  "password": "Test1234!"
}
###

POST {{OneTime.Api_HostAddress}}/api/auths/login
Content-Type: application/json

{
  "email": "Employee@jndata.dk",
  "password": "!1234Test"
}
###

POST {{OneTime.Api_HostAddress}}/api/projects
Content-Type: application/json
Accept: application/json

{
  "name": "delete",
  "status": 0
}
###
DELETE {{OneTime.Api_HostAddress}}/api/projects/14
###
PUT {{OneTime.Api_HostAddress}}/api/projects/2
Content-Type: application/json

{
  "name": "testupdated?",
  "status": 2
}