// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OneTime.Core.Models;

[Table("AuditLog")]
public partial class AuditLog
{
    [Key]
    public int AuditLogId { get; set; }

    public int? ActorUserId { get; set; }

    [Required]
    [StringLength(100)]
    public string EntityType { get; set; }

    public int EntityId { get; set; }

    [Precision(0)]
    public DateTime OccurredAt { get; set; }

    public string Before { get; set; }

    public string After { get; set; }

    [StringLength(100)]
    public string CorrelationId { get; set; }

    [Required]
    [StringLength(100)]
    public string Action { get; set; }

    [ForeignKey("ActorUserId")]
    [InverseProperty("AuditLogs")]
    public virtual JNUser ActorUser { get; set; }
}