// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using OneTime.Core.Models.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OneTime.Core.Models;

public partial class JNUser
{
    [Key]
    public int UserId { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [Required]
    [StringLength(255)]
    public string Email { get; set; }

    [Required]
    [StringLength(255)]
    public string PasswordHash { get; set; }

    [Required]
    [StringLength(255)]
    public string PasswordSalt { get; set; }

	public UserRole Role { get; set; }
	public int? ManagerId { get; set; }

    // Self-reference: én manager til mange TeamMembers
    [ForeignKey("ManagerId")]
    [InverseProperty("TeamMembers")]
    public virtual JNUser Manager { get; set; }

    [InverseProperty("Manager")]
    public virtual ICollection<JNUser> TeamMembers { get; set; } = new List<JNUser>();

    [InverseProperty("ActorUser")]
    public virtual ICollection<AuditLog> AuditLogs { get; set; } = new List<AuditLog>();

    // FK ligger på Notification (typisk Notification.UserId), så ingen [ForeignKey] her
    [InverseProperty("User")]
    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    [InverseProperty("User")]
    public virtual ICollection<TimeEntry> TimeEntries { get; set; } = new List<TimeEntry>();

    [InverseProperty("DecidedByUser")]
    public virtual ICollection<Timesheet> TimesheetDecidedByUsers { get; set; } = new List<Timesheet>();

    [InverseProperty("User")]
    public virtual ICollection<Timesheet> TimesheetUsers { get; set; } = new List<Timesheet>();
}
