// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OneTime.Core.Models;

public partial class JNUser
{
    [Key]
    public int UserId { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [Required]
    [StringLength(255)]
    public string Email { get; set; }

    [Required]
    [StringLength(255)]
    public string PasswordHash { get; set; }

    [Required]
    [StringLength(255)]
    public string PasswordSalt { get; set; }

    [Required]
    [StringLength(50)]
    public string Role { get; set; }

    public int? ManagerId { get; set; }

    [ForeignKey("ManagerId")]
    [InverseProperty("TeamMembers")]
    public virtual JNUser Manager { get; set; }

    public int? ManagerId { get; set; }

    [InverseProperty("ActorUser")]
    public virtual ICollection<AuditLog> AuditLogs { get; set; } = new List<AuditLog>();

    [InverseProperty("Manager")]
    public virtual ICollection<JNUser> TeamMembers { get; set; } = new List<JNUser>();

	[InverseProperty("DecidedByUser")]
    public virtual ICollection<MonthlyReview> MonthlyReviewDecidedByUsers { get; set; } = new List<MonthlyReview>();

    [ForeignKey("ManagerId")]
    [InverseProperty("InverseManager")]
    public virtual JNUser Manager { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    [InverseProperty("User")]
    public virtual ICollection<TimeEntry> TimeEntries { get; set; } = new List<TimeEntry>();

    [InverseProperty("DecidedByUser")]
    public virtual ICollection<Timesheet> TimesheetDecidedByUsers { get; set; } = new List<Timesheet>();

    [InverseProperty("User")]
    public virtual ICollection<Timesheet> TimesheetUsers { get; set; } = new List<Timesheet>();
}