// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OneTime.Core.Models;

public partial class MonthlyReview
{
    [Key]
    public int MonthlyReviewId { get; set; }

    public int UserId { get; set; }

    public DateOnly PeriodStart { get; set; }

    public DateOnly PeriodEnd { get; set; }

    public int? DecidedByUserId { get; set; }

    [Precision(0)]
    public DateTime? DecidedAt { get; set; }

    public string Comment { get; set; }

    [Required]
    [StringLength(50)]
    public string Status { get; set; }

    [ForeignKey("DecidedByUserId")]
    [InverseProperty("MonthlyReviewDecidedByUsers")]
    public virtual JNUser DecidedByUser { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("MonthlyReviewUsers")]
    public virtual JNUser User { get; set; }
}