// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OneTime.Core.Models;

public partial class Notification
{
    [Key]
    public int NotificationId { get; set; }

    public int UserId { get; set; }

    public int? RelatedEntityId { get; set; }

    [Precision(0)]
    public DateTime SentAt { get; set; }

    [Precision(0)]
    public DateTime? ReadAt { get; set; }

    [Required]
    [StringLength(50)]
    public string Type { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Notifications")]
    public virtual JNUser User { get; set; }
}