// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace OneTime.Core.Models;

public partial class OneTimeContext : DbContext
{
    public OneTimeContext(DbContextOptions<OneTimeContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AuditLog> AuditLogs { get; set; }

    public virtual DbSet<JNUser> JNUsers { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<Project> Projects { get; set; }

    public virtual DbSet<SystemConfig> SystemConfigs { get; set; }

    public virtual DbSet<TimeEntry> TimeEntries { get; set; }

    public virtual DbSet<Timesheet> Timesheets { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AuditLog>(entity =>
        {
            entity.HasOne(d => d.ActorUser).WithMany(p => p.AuditLogs).HasConstraintName("FK_AuditLog_ActorUser");
        });

        modelBuilder.Entity<JNUser>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK_User");

            entity.HasOne(d => d.Manager).WithMany(p => p.InverseManager).HasConstraintName("FK_JNUsers_Manager");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.NotificationId).HasName("PK_Notification");

            entity.HasOne(d => d.User).WithMany(p => p.Notifications)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Notification_User");
        });

        modelBuilder.Entity<Project>(entity =>
        {
            entity.HasKey(e => e.ProjectId).HasName("PK_Project");
        });

        modelBuilder.Entity<SystemConfig>(entity =>
        {
            entity.HasKey(e => e.ConfigId).HasName("PK_SystemConfig");
        });

        modelBuilder.Entity<TimeEntry>(entity =>
        {
            entity.HasKey(e => e.TimeEntryId).HasName("PK_TimeEntry");

            entity.HasOne(d => d.Project).WithMany(p => p.TimeEntries)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TimeEntry_Project");

            entity.HasOne(d => d.User).WithMany(p => p.TimeEntries)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TimeEntry_User");
        });

        modelBuilder.Entity<Timesheet>(entity =>
        {
            entity.HasKey(e => e.TimesheetId).HasName("PK_Timesheet");

            entity.HasOne(d => d.DecidedByUser).WithMany(p => p.TimesheetDecidedByUsers).HasConstraintName("FK_Timesheet_DecidedByUser");

            entity.HasOne(d => d.User).WithMany(p => p.TimesheetUsers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Timesheet_User");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseSqlServer(Secret.ConnectionString);
        }

    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}