// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OneTime.Core.Models;

public partial class SystemConfig
{
    [Key]
    public int ConfigId { get; set; }

    public DateOnly WorkPeriodStartDate { get; set; }

    public DateOnly WorkPeriodEndDate { get; set; }

    public int WeeklyMaxHours { get; set; }
}