// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OneTime.Core.Models;

public partial class TimeEntry
{
    [Key]
    public int TimeEntryId { get; set; }

    public int UserId { get; set; }

    public int ProjectId { get; set; }

    public DateOnly Date { get; set; }

    public string Note { get; set; }

    [Column(TypeName = "decimal(4, 2)")]
    public decimal Hours { get; set; }

    public int TimesheetId { get; set; }

    [ForeignKey("ProjectId")]
    [InverseProperty("TimeEntries")]
    public virtual Project Project { get; set; }

    [ForeignKey("TimesheetId")]
    [InverseProperty("TimeEntries")]
    public virtual Timesheet Timesheet { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("TimeEntries")]
    public virtual JNUser User { get; set; }
}