// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OneTime.Core.Models;

[Index("UserId", "PeriodStart", "PeriodEnd", Name = "UQ_Timesheet_User_Period", IsUnique = true)]
public partial class Timesheet
{
    [Key]
    public int TimesheetId { get; set; }

    public int UserId { get; set; }

    public DateOnly PeriodStart { get; set; }

    public DateOnly PeriodEnd { get; set; }

    public int? DecidedByUserId { get; set; }

    [Precision(0)]
    public DateTime? DecidedAt { get; set; }

    public string Comment { get; set; }

    public int Status { get; set; }

    [ForeignKey("DecidedByUserId")]
    [InverseProperty("TimesheetDecidedByUsers")]
    public virtual JNUser DecidedByUser { get; set; }

    [InverseProperty("Timesheet")]
    public virtual ICollection<TimeEntry> TimeEntries { get; set; } = new List<TimeEntry>();

    [ForeignKey("UserId")]
    [InverseProperty("TimesheetUsers")]
    public virtual JNUser User { get; set; }
}