// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using OneTime.Core.Models.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OneTime.Core.Models;

public partial class Timesheet
{
    [Key]
    public int TimesheetId { get; set; }

    public int UserId { get; set; }

    public DateOnly PeriodStart { get; set; }

    public DateOnly PeriodEnd { get; set; }

    public int? DecidedByUserId { get; set; }

    [Precision(0)]
    public DateTime? DecidedAt { get; set; }

    public string Comment { get; set; }

	public TimesheetStatus Status { get; set; }

	[ForeignKey("DecidedByUserId")]
    [InverseProperty("TimesheetDecidedByUsers")]
    public virtual JNUser DecidedByUser { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("TimesheetUsers")]
    public virtual JNUser User { get; set; }
}